spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://db.qwitwaexzjkoxuuokjau.supabase.co:5432/postgres?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: Saha@6462++
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_1
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html
    syntax-highlight:
      theme: agate